USE [master]
GO
/****** Object:  Database [florenciaDB]    Script Date: 10/9/25 4:54:41AM ******/
CREATE DATABASE [florenciaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'florenciaDB', FILENAME = N'/var/opt/mssql/data/florenciaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'florenciaDB_log', FILENAME = N'/var/opt/mssql/data/florenciaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [florenciaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [florenciaDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [florenciaDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [florenciaDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [florenciaDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [florenciaDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [florenciaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [florenciaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [florenciaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [florenciaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [florenciaDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [florenciaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [florenciaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [florenciaDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [florenciaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [florenciaDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [florenciaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [florenciaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [florenciaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [florenciaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [florenciaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [florenciaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [florenciaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [florenciaDB] SET RECOVERY FULL 
GO
ALTER DATABASE [florenciaDB] SET  MULTI_USER 
GO
ALTER DATABASE [florenciaDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [florenciaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [florenciaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [florenciaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [florenciaDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'florenciaDB', N'ON'
GO
ALTER DATABASE [florenciaDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [florenciaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
USE [florenciaDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET CE_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DOP_FEEDBACK = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET FORCE_SHOWPLAN_RUNTIME_PARAMETER_COLLECTION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEDGER_DIGEST_STORAGE_ENDPOINT = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERSISTENCE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES = 1440;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO
USE [florenciaDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10/9/25 4:54:41AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Categories]    Script Date: 10/9/25 4:54:45AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 10/9/25 4:54:45AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[OrderItemId] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[UnitPrice] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Orders]    Script Date: 10/9/25 4:54:45AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[OrderDate] [datetime] NULL,
	[Status] [nvarchar](50) NULL,
	[TotalAmount] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Products]    Script Date: 10/9/25 4:54:45AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryId] [int] NOT NULL,
	[ProductName] [nvarchar](150) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[Stock] [int] NOT NULL,
	[ImageUrl] [nvarchar](255) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Users]    Script Date: 10/9/25 4:54:45AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Categories] ON 

INSERT [dbo].[Categories] ([CategoryId], [CategoryName], [Description]) VALUES (1, N'Men', N'Men fashion and accessories')
INSERT [dbo].[Categories] ([CategoryId], [CategoryName], [Description]) VALUES (2, N'Women', N'Women fashion and accessories')
INSERT [dbo].[Categories] ([CategoryId], [CategoryName], [Description]) VALUES (3, N'Shoes', N'Footwear for men and women')
SET IDENTITY_INSERT [dbo].[Categories] OFF
SET IDENTITY_INSERT [dbo].[Products] ON 

INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (1, 3, N'Classic Leather Sneakers', N'White low-top leather sneakers', CAST(69.99 AS Decimal(10, 2)), 150, N'images/shoes/shoes2.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (2, 3, N'High-Top Canvas Sneakers', N'Black canvas high-top sneakers', CAST(59.99 AS Decimal(10, 2)), 120, N'images/shoes/shoes3.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (3, 3, N'Luxury Silk Slip-Ons', N'Handmade silk slip-on shoes with embroidery', CAST(129.99 AS Decimal(10, 2)), 40, N'images/shoes/shoes4.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (4, 3, N'Regano Sport Runners', N'Lightweight running sneakers with cushioning', CAST(79.99 AS Decimal(10, 2)), 180, N'images/shoes/shoes2.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (5, 3, N'Suede Desert Boots', N'Brown suede ankle boots', CAST(99.99 AS Decimal(10, 2)), 75, N'images/shoes/shoes3.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (6, 3, N'Regano Elegance Loafers', N'Premium leather loafers for evening wear', CAST(119.99 AS Decimal(10, 2)), 60, N'images/shoes/shoes4.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (7, 3, N'Chic Platform Sneakers', N'White platform sneakers for women', CAST(84.99 AS Decimal(10, 2)), 90, N'images/shoes/shoes2.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
INSERT [dbo].[Products] ([ProductId], [CategoryId], [ProductName], [Description], [Price], [Stock], [ImageUrl], [CreatedAt]) VALUES (8, 3, N'Winter Leather Boots', N'Black insulated leather boots for winter', CAST(139.99 AS Decimal(10, 2)), 50, N'images/shoes/shoes3.webp', CAST(N'2025-09-30T09:49:39.620' AS DateTime))
SET IDENTITY_INSERT [dbo].[Products] OFF
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ__Users__A9D10534D0789799]    Script Date: 10/9/25 4:54:45AM ******/
ALTER TABLE [dbo].[Users] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT (getdate()) FOR [OrderDate]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT ('Pending') FOR [Status]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([OrderId])
REFERENCES [dbo].[Orders] ([OrderId])
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([ProductId])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([CategoryId])
GO
USE [master]
GO
ALTER DATABASE [florenciaDB] SET  READ_WRITE 
GO
